package com.github.romanqed.unpackr.asm;

import com.github.romanqed.asm.sorter.LocalVariablesSorter;
import com.github.romanqed.asm.sorter.LocalVariablesWriter;
import com.github.romanqed.jeflect.loader.DefineClassLoader;
import com.github.romanqed.jeflect.loader.DefineLoader;
import com.github.romanqed.jeflect.loader.DefineObjectFactory;
import com.github.romanqed.jeflect.loader.ObjectFactory;
import com.github.romanqed.unpackr.Caller;
import com.github.romanqed.unpackr.MemberAccess;
import com.github.romanqed.unpackr.Unpacker;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Objects;
import java.util.function.Consumer;

/**
 * An {@link Unpacker} implementation that generates unpacking logic using runtime bytecode generation
 * via the ASM library.
 * <p>
 * This class dynamically creates and defines a new implementation of the {@link Caller} interface,
 * where the {@code apply} method is compiled into efficient bytecode to invoke the specified {@code target}
 * method with parameters extracted from the given {@link MemberAccess} chains.
 * <p>
 * This approach allows the unpacking logic to be inlined and optimized by the JVM at runtime,
 * avoiding the overhead of reflection.
 *
 * <h3>Usage Example</h3>
 * Suppose we have a class {@code Ctx} with methods {@code getRq()} and {@code getRp()},
 * and their return types have methods {@code getRqProps()} and {@code getRpProps()} respectively.
 * The goal is to invoke a method that accepts the results of those nested calls.
 *
 * <pre>{@code
 * var unpacker = new AsmUnpacker(new DefineClassLoader());
 * var method = Target.class.getMethod("handle", Map.class, Map.class);
 * var rqPropsAccess = MemberAccess.of()
 *           .of(Ctx.class)
 *           .of(Ctx.class.getMethod("getRq"))
 *           .of(Rq.class.getMethod("getRqProps"))
 *           .build();
 * var rpPropsAccess = MemberAccess.of()
 *           .of(Ctx.class)
 *           .of(Ctx.class.getMethod("getRp"))
 *           .of(Rp.class.getMethod("getRpProps"))
 *           .build();
 * var caller = unpacker.unpack(Ctx.class, method, rqPropsAccess, rpPropsAccess);
 * }</pre>
 * <p>
 * This caller can now be used to dynamically extract data from a {@code Ctx} instance
 * and pass it to the target method.
 *
 * @see com.github.romanqed.unpackr.Unpacker
 * @see com.github.romanqed.unpackr.MemberAccess
 * @see com.github.romanqed.unpackr.MemberAccessBuilder
 */
public final class AsmUnpacker implements Unpacker {
    private static final String METHOD_NAME = "call";
    private static final String METHOD_DESCRIPTOR = "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;";
    private static final String THROWABLE = "java/lang/Throwable";
    private static final String CALLER = Type.getInternalName(Caller.class);
    private final ObjectFactory<Caller> factory;

    /**
     * Constructs a new {@code AsmUnpacker} with a custom {@link ObjectFactory}
     * for defining generated unpacker classes.
     *
     * @param factory the factory used to define generated classes, must not be {@code null}
     */
    public AsmUnpacker(ObjectFactory<Caller> factory) {
        this.factory = Objects.requireNonNull(factory);
    }

    /**
     * Constructs a new {@code AsmUnpacker} using the specified {@link DefineLoader} to define generated classes.
     *
     * @param loader the loader to define generated classes with
     */
    public AsmUnpacker(DefineLoader loader) {
        this.factory = new DefineObjectFactory<>(loader);
    }

    /**
     * Constructs a new {@code AsmUnpacker} using a default {@link DefineClassLoader}
     * as the underlying class definition mechanism.
     * <p>
     * This constructor is a convenient shorthand equivalent to:
     * <pre>{@code
     * new AsmUnpacker(new DefineObjectFactory<>(new DefineClassLoader()));
     * }</pre>
     * <p>
     * The generated bytecode classes will be defined in an isolated,
     * runtime-created class loader to prevent class name conflicts and
     * allow garbage collection of dynamically generated classes when no longer referenced.
     */
    public AsmUnpacker() {
        this.factory = new DefineObjectFactory<>(new DefineClassLoader());
    }

    private static Consumer<MethodVisitor> buildRootLoader(LocalVariablesSorter visitor, Class<?> packed, int size) {
        var type = Type.getType(packed);
        var typeName = type.getInternalName();
        if (size < 2) {
            return v -> {
                v.visitVarInsn(Opcodes.ALOAD, 2);
                v.visitTypeInsn(Opcodes.CHECKCAST, typeName);
            };
        }
        var index = visitor.newLocal(type);
        visitor.visitVarInsn(Opcodes.ALOAD, 2);
        visitor.visitTypeInsn(Opcodes.CHECKCAST, typeName);
        visitor.visitVarInsn(Opcodes.ASTORE, index);
        return v -> v.visitVarInsn(Opcodes.ALOAD, index);
    }

    private static void invokeTargetMethod(MethodVisitor visitor, Method target) {
        AsmUtil.invoke(visitor, target);
        var type = target.getReturnType();
        if (type == void.class) {
            visitor.visitInsn(Opcodes.ACONST_NULL);
        } else if (type.isPrimitive()) {
            AsmUtil.packPrimitive(visitor, type);
        }
    }

    private static void generateDirectCall(MethodVisitor visitor,
                                           Class<?> packed,
                                           Method target,
                                           Consumer<MethodVisitor> loader) {
        // {
        visitor.visitCode();
        // Prepare method owner ref
        if (!Modifier.isStatic(target.getModifiers())) {
            visitor.visitVarInsn(Opcodes.ALOAD, 1);
            visitor.visitTypeInsn(Opcodes.CHECKCAST, Type.getInternalName(target.getDeclaringClass()));
        }
        var types = target.getParameterTypes();
        for (var type : types) {
            if (type != packed) {
                throw new IllegalArgumentException("Mismatched types: " + type + ", " + packed);
            }
            loader.accept(visitor);
        }
        invokeTargetMethod(visitor, target);
        visitor.visitInsn(Opcodes.ARETURN);
        // }
        visitor.visitMaxs(0, 0);
        visitor.visitEnd();
    }

    private static void generateMethod(LocalVariablesSorter visitor,
                                       ConstantPusher pusher,
                                       Class<?> packed,
                                       Method target,
                                       MemberAccess[][] accesses) {
        // Build the access tree
        var count = new int[1];
        var node = NodeUtil.of(accesses, count);
        var children = node.children;
        // Check shortcut
        if (children == null) {
            var loader = buildRootLoader(visitor, packed, count[0]);
            generateDirectCall(visitor, packed, target, loader);
            return;
        }
        var loader = buildRootLoader(visitor, packed, count[0] + children.size());
        node.accessor = loader;
        // Generate cache vars and prepare arg loaders
        var nodeVisitor = new AsmNodeVisitor(visitor, pusher, accesses.length);
        node.accept(nodeVisitor);
        // {
        visitor.visitCode();
        // Prepare method owner ref
        if (!Modifier.isStatic(target.getModifiers())) {
            visitor.visitVarInsn(Opcodes.ALOAD, 1);
            visitor.visitTypeInsn(Opcodes.CHECKCAST, Type.getInternalName(target.getDeclaringClass()));
        }
        // Invoke loaders
        var loaders = nodeVisitor.loaders;
        var types = nodeVisitor.types;
        var argTypes = target.getParameterTypes();
        for (var i = 0; i < loaders.length; ++i) {
            var argType = argTypes[i];
            if (argType == packed) {
                loader.accept(visitor);
                continue;
            }
            loaders[i].accept(visitor);
            AsmUtil.castReference(visitor, types[i], argType);
        }
        invokeTargetMethod(visitor, target);
        visitor.visitInsn(Opcodes.ARETURN);
        // }
        visitor.visitMaxs(0, 0);
        visitor.visitEnd();
    }

    private static byte[] generateUnpacker(String name,
                                           ConstantPusher pusher,
                                           Class<?> packed,
                                           Method target,
                                           MemberAccess[][] accesses) {
        var writer = new LocalVariablesWriter(ClassWriter.COMPUTE_MAXS);
        writer.visit(
                Opcodes.V11,
                Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                name,
                null,
                AsmUtil.OBJECT_NAME,
                new String[]{CALLER}
        );
        pusher.declare(writer);
        var visitor = writer.visitMethodWithLocals(
                Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                METHOD_NAME,
                METHOD_DESCRIPTOR,
                null,
                new String[]{THROWABLE}
        );
        generateMethod(visitor, pusher, packed, target, accesses);
        writer.visitEnd();
        return writer.toByteArray();
    }

    private static byte[] generateDirectCaller(String name, Method target) {
        var writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        writer.visit(
                Opcodes.V11,
                Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                name,
                null,
                AsmUtil.OBJECT_NAME,
                new String[]{CALLER}
        );
        AsmUtil.createEmptyConstructor(writer);
        var visitor = writer.visitMethod(
                Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                METHOD_NAME,
                METHOD_DESCRIPTOR,
                null,
                new String[]{THROWABLE}
        );
        invokeTargetMethod(visitor, target);
        visitor.visitInsn(Opcodes.ARETURN);
        visitor.visitMaxs(0, 0);
        visitor.visitEnd();
        writer.visitEnd();
        return writer.toByteArray();
    }

    @Override
    public Caller unpack(Class<?> packed, Method target, MemberAccess[]... accesses) {
        if (!Modifier.isPublic(target.getModifiers())) {
            throw new IllegalArgumentException("Target method must be public");
        }
        var count = target.getParameterCount();
        if (count != accesses.length) {
            throw new IllegalArgumentException(
                    "The size of the accesses array does not match the parameters of the target method"
            );
        }
        var name = "Unpacker" + packed.hashCode() + ":" + target.hashCode();
        if (count == 0) {
            return factory.create(name, () -> generateDirectCaller(name, target));
        }
        var pusher = ConstantPusher.of(name, accesses);
        var array = pusher.buildArray();
        return factory.create(
                name,
                () -> generateUnpacker(name, pusher, packed, target, accesses),
                clazz -> {
                    if (array == null) {
                        var ctor = clazz.getConstructor();
                        ctor.setAccessible(true);
                        return (Caller) ctor.newInstance((Object[]) null);
                    }
                    var ctor = clazz.getConstructor(Object[].class);
                    ctor.setAccessible(true);
                    return (Caller) ctor.newInstance(new Object[]{array});
                }
        );
    }
}
