/**
 * Provides a high-performance implementation of the {@link com.github.romanqed.unpackr.Unpacker Unpacker}
 * based on runtime bytecode generation via the ASM library.
 * <p>
 * This module dynamically generates optimized {@code Caller} implementations that unpack and invoke
 * target methods without reflection overhead. The generated bytecode is designed to be
 * JVM-friendly and suitable for just-in-time (JIT) inlining, providing near-native invocation speed.
 * <p>
 * The core entry point of this module is {@link com.github.romanqed.unpackr.asm.AsmUnpacker AsmUnpacker},
 * which can produce efficient unpackers for arbitrary method signatures using {@link com.github.romanqed.unpackr.MemberAccess}
 * descriptors.
 * <p>
 * Internally, this module relies on:
 * <ul>
 *     <li>{@code org.objectweb.asm} — for direct bytecode emission;</li>
 *     <li>{@code com.github.romanqed.asm.sorter} — to manage local variable indices;</li>
 *     <li>{@code com.github.romanqed.jeflect.loader} — to define generated classes at runtime.</li>
 * </ul>
 *
 * <h2>Example</h2>
 * <pre>{@code
 * var unpacker = new AsmUnpacker();
 * var method = Target.class.getMethod("handle", Map.class, Map.class);
 * var rq = MemberAccess.of().of(Ctx.class).of(Ctx.class.getMethod("getRq")).build();
 * var rp = MemberAccess.of().of(Ctx.class).of(Ctx.class.getMethod("getRp")).build();
 * var caller = unpacker.unpack(Ctx.class, method, rq, rp);
 * }</pre>
 *
 * @see com.github.romanqed.unpackr.Unpacker
 * @see com.github.romanqed.unpackr.asm.AsmUnpacker
 * @see org.objectweb.asm
 */
module com.github.romanqed.unpackr.asm {
    // Imports
    requires org.objectweb.asm;
    requires com.github.romanqed.asm.sorter;
    requires com.github.romanqed.unpackr;
    requires com.github.romanqed.jfunc;
    requires com.github.romanqed.jeflect.loader;
    // Exports
    exports com.github.romanqed.unpackr.asm;
}
